repos:
  - repo: local
    hooks:
      - id: dart-analyze
        name: dart analyze
        entry: dart analyze
        language: system
        types: [dart]
        pass_filenames: false

      - id: dart-format
        name: dart format
        entry: dart format
        language: system
        types: [dart]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
