repos:
  - repo: local
    hooks:
      - id: dart-analyze
        name: dart analyze
        entry: dart analyze
        language: system
        types: [dart]
        pass_filenames: false
      - id: dart-format
        name: dart format
        entry: dart format
        language: system
        types: [dart]
        pass_filenames: false